export const Shop = [
  {
    id: "0",
    title: "'Shop'",
    image: process.env.PUBLIC_URL + "/ShopImages/TopShopImage.png",
    price: null,
    bio: null,
     bio2: null,
 material: null,
    color: null,
measurements: null,
  },
  {
    id: "1",
    title: "'Balance' Vase",
    image: process.env.PUBLIC_URL + "/ShopImages/tanVaseBlueBall.png",
    price: "$79.99",
      bio: "Beautiful hand-made vase with the most gorgeous think brown matte glaze.",
     bio2: "This piece is handmade in stoneware clay and one of a kind.",
 material: "Material: Stoneware clay; matte glaze.",
    color: "Color: Brown",
measurements: "Measurements: 35x20 cm",
      
  },
  {
    id: "2",
    title: "'Binocular' Vase",
    image: process.env.PUBLIC_URL + "/ShopImages/greenVaseBluePuck.png",
    price: "$49.99",
    bio: "Striking sculpture vase with a gorgeuos matter navy glaze. Each piece is handmade with slight variations.",
    bio2: " ",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Navy",
measurements: "Measurements: 32x8 cm",
  },
  {
    id: "3",
    title: "'Bubble' Flowerpot",
    image: process.env.PUBLIC_URL + "/ShopImages/orangeBallGreenStem.png",
    price: "$49.99",
    bio: "Beautiful hand-made flowerpot with the most gorgeous thick orange matte glaze. The flowerpot has a hole for drainage.",
    bio2: "This piece is handmade in stoneware clay and one of a kind.",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Orange",
measurements: "Measurements: 15x15 cm",
  },
  {
    id: "4",
    title: "'Bulb' Vase",
    image: process.env.PUBLIC_URL + "/ShopImages/greyVasePurpleRag.png",
    price: "$59.99",
    bio: "A sweet bud vase that's perfect for layering with other pieces.",
    bio2: "Handmand and finished in a soft purple-grey glaze.",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Lavender",
measurements: "Measurements: 14x14 cm",
  },
  {
    id: "5",
    title: "'Candy' Flowerpot",
    image: process.env.PUBLIC_URL + "/ShopImages/yellowVaseCactus.png",
    price: "$39.99",
    bio: "Beautiful hand-made flowerpot with the most gorgeous thick yellow matte glaze. The flowerpot has a hole for drainage.",
    bio2: "This piece is handmade in stoneware clay and one of a kind.",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Yellow",
measurements: "Measurements: 10x10",
  },
  {
    id: "6",
    title: "'Drop' Vase",
    image: process.env.PUBLIC_URL + "/ShopImages/whiteVaseTwoPucksTanPur.png",
    price: "$49.99",
    bio: "Gorgeous textured bud vase with a matter ivory glaze. Try using a few as a dining table centerpiece.",
    bio2: " ",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Ivory",
measurements: "Measurements: 18x12 cm",
  },

  {
    id: "7",
    title: "'Mango' Flowerpot",
    image: process.env.PUBLIC_URL + "/ShopImages/yellowVaseTwoArches.png",
    price: "$49.99",
    bio: "Tall and sleek, this yellow vase will never go out of style.",
    bio2: "Handmade in stoneware clay with a matte finish.",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Yellow",
measurements: "Measurements: 18x12 cm",
  },
  {
    id: "8",
    title: "'Sun' Vase",
    image: process.env.PUBLIC_URL + "/ShopImages/yellowVase-U-Aside.png",
    price: "$69.99",
    bio: "Organic texture finish on a striking shape, this vase is one of a kind. Handmade and hand-textured in stoneware clay.",
    bio2: " ",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Yellow",
measurements: "Measurements: 15x10 cm",
  },

  {
    id: "9",
    title: "'Wave' Vase",
    image: process.env.PUBLIC_URL + "/ShopImages/tanTribelDisc.png",
    price: "$69.99",
    bio: "Inspired by the female figure, a beautiful vase for one or two stems. Finish in a soft purple-grey glaze.",
    bio2: " ",
material: "Material: Stoneware clay; matte glaze.",
   color: "Color: Lavender",
measurements: "Measurements: 30x18 cm",
  },
];
